Support Swift 4.1
hasadna/Anyway-iOS pull request #14
Opened 2018-09-25 08:12 UTC by yigalomer

2018-09-25 12:20 UTC, avielg commented on Anyway/DetailViewController.swift
> +            self?.vehicles = vehicleList ;//$0.1
nit: drop the comments

2018-09-25 12:21 UTC, avielg commented on Anyway/MarkerViews.swift
> +
nit: kill whitespace & commented line

2018-09-25 12:22 UTC, avielg commented on Anyway/Utilities.swift
> +   /* func attributedStringFromHTMLString(_ overrideFont: Bool = false, color: UIColor = UIColor.white) -> NSAttributedString {
why function commented?

2018-09-25 12:23 UTC, avielg commented on Anyway/ViewController+MapView.swift
> +
nit: kill

2018-09-25 12:23 UTC, avielg commented on Anyway/ViewController+MapView.swift
> +         }
nit: indent

2018-09-25 12:24 UTC, avielg commented on Anyway/ViewController+MapView.swift
> +        //?? YIGAL what is this ?
nit: drop

2018-09-25 12:28 UTC, avielg commented on Anyway/ViewController+MapView.swift
> +
nit: whitespace

2018-09-25 12:28 UTC, avielg commented on Anyway/ViewController+MapView.swift
> +
nit: whitespace

2018-09-25 12:28 UTC, avielg commented on Anyway/ViewController+MapView.swift
> +        print("mapView:didSelect")
nit: drop comment

2018-09-25 12:28 UTC, avielg commented on Anyway/ViewController.swift
> +
nit: whitespace & comment

2018-09-25 12:29 UTC, avielg requested changes
few nits, otherwise looks good

Thanks!

2018-09-25 12:31 UTC, avielg approved these changes
where is -180,-180? 🤔

2018-09-25 12:32 UTC, avielg requested changes
goddammit github…. I didn't realize the 2 commits are together… anyway the 2 one looks good, just go over the nits in the first one

2018-09-25 13:22 UTC, yigalomer commented on Anyway/Utilities.swift
> +   /* func attributedStringFromHTMLString(_ overrideFont: Bool = false, color: UIColor = UIColor.white) -> NSAttributedString {
Never used, made some compilation errors

2018-09-25 13:23 UTC, avielg commented on Anyway/Utilities.swift
> +   /* func attributedStringFromHTMLString(_ overrideFont: Bool = false, color: UIColor = UIColor.white) -> NSAttributedString {
oh then feel free to delete it 👍 
if we ever need it again we have source control (:

2018-09-25 13:35 UTC, yigalomer commented
I saw that member lastRegion =-180,-180  when app start  when we call "var lastRegion = MKCoordinateRegionForMapRect(MKMapRectNull)"

I needed a way to get annotations when app starts

Didn't find another way to check for null on lastRegion - do you know a way?

2018-09-25 13:36 UTC, yigalomer commented on Anyway/ViewController.swift
> +
what is "nit"?

2018-09-25 13:49 UTC, yigalomer commented on Anyway/ViewController+MapView.swift
> +         }
Fixed

2018-09-25 13:49 UTC, yigalomer commented on Anyway/ViewController+MapView.swift
> +
fixed

2018-09-25 13:49 UTC, yigalomer commented on Anyway/Utilities.swift
> +   /* func attributedStringFromHTMLString(_ overrideFont: Bool = false, color: UIColor = UIColor.white) -> NSAttributedString {
fixed

2018-09-25 13:49 UTC, yigalomer commented on Anyway/MarkerViews.swift
> +
fixed

2018-09-25 13:50 UTC, yigalomer commented on Anyway/ViewController+MapView.swift
> +
fixed

2018-09-25 13:50 UTC, yigalomer commented on Anyway/ViewController+MapView.swift
> +
fixed

2018-09-25 13:51 UTC, yigalomer commented on Anyway/ViewController+MapView.swift
> +        print("mapView:didSelect")
fixed

2018-09-25 13:52 UTC, yigalomer commented on Anyway/ViewController.swift
> +
fixed

2018-10-22 17:11 UTC, avielg approved these changes

2018-10-22 17:17 UTC, merged